repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: \.ipynb

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.1'
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check
        args: [--fix]
        language: system
        types_or: [python, jupyter]
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format
        language: system
        types_or: [python, jupyter]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        args: ["--disallow-untyped-defs"]
        language: system
        types: [python]
      # - id: pytest
      #   name: pytest
      #   entry: poetry run pytest
      #   language: system
      #   types: [python]
